package mysql

import (
	"encoding/json"
	"log"
	"os"
)

func InitMysqlFile() {
	filePtr, err := os.Open("D:\\GoDevelop\\GoProject\\demo\\mysql_common\\mysql\\setting.json")
	if err != nil {
		log.Printf("文件打开失败 [Err:%s]", err.Error())
		return
	}

	defer filePtr.Close()
	// 创建json解码器
	info := AutoGenerated{}

	decoder := json.NewDecoder(filePtr)
	err = decoder.Decode(&info)
	if err != nil {
		log.Println("mysql解码失败", err.Error())
	}

	//初始化数据库
	for _, v := range info.Database {
		d1 := v.DB1

		conf1 := DBConfig{
			DsName:   d1.DsName,
			Host:     d1.Host,
			Port:     d1.Port,
			Database: d1.Database,
			Username: d1.Username,
			Password: d1.Password,
		}

		BuildByConfig(conf1)

	}

}

// --json转实体
type AutoGenerated struct {
	Database []Database `json:"database"`
}

type DB1 struct {
	DsName   string `json:"dsName"`
	Host     string `json:"host"`
	Port     string `json:"port"`
	Username string `json:"username"`
	Password string `json:"password"`
	Database string `json:"database"`
	Type     string `json:"type"`
}

type Database struct {
	DB1 DB1 `json:"DB1"`
}
